// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddMediaItems implements pgx.CopyFromSource.
type iteratorForAddMediaItems struct {
	rows                 []AddMediaItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddMediaItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddMediaItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].BucketPath,
		r.rows[0].RequiredMimeType,
		r.rows[0].UploadType,
		r.rows[0].UploadID,
	}, nil
}

func (r iteratorForAddMediaItems) Err() error {
	return nil
}

func (q *Queries) AddMediaItems(ctx context.Context, arg []AddMediaItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"global", "media"}, []string{"id", "bucket_path", "required_mime_type", "upload_type", "upload_id"}, &iteratorForAddMediaItems{rows: arg})
}
