// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: global_users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGlobalUser = `-- name: CreateGlobalUser :execrows
INSERT INTO
	global.users (id, email)
VALUES
	($1, $2)
ON CONFLICT (id) DO NOTHING
`

type CreateGlobalUserParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) CreateGlobalUser(ctx context.Context, arg CreateGlobalUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, createGlobalUser, arg.ID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGlobalUsersByQuery = `-- name: GetGlobalUsersByQuery :many
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
WHERE
	normalized_name ILIKE '%' || unaccent (
		$2::TEXT
	) || '%'
	OR normalized_email ILIKE '%' || unaccent (
		$2::TEXT
	) || '%'
ORDER BY
	created_at DESC
LIMIT
	$1
`

type GetGlobalUsersByQueryParams struct {
	Limit int32  `json:"limit"`
	Query string `json:"query"`
}

func (q *Queries) GetGlobalUsersByQuery(ctx context.Context, arg GetGlobalUsersByQueryParams) ([]GlobalUserDetail, error) {
	rows, err := q.db.Query(ctx, getGlobalUsersByQuery, arg.Limit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalUserDetail
	for rows.Next() {
		var i GlobalUserDetail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.About,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.ProfilePictureID,
			&i.Status,
			&i.UncompressedProfilePicture,
			&i.ProfilePictureSize,
			&i.ProfilePictureStatus,
			&i.Thumbnail,
			&i.Small,
			&i.Medium,
			&i.Large,
			&i.ExtraLarge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalUsersLatestFirst = `-- name: GetGlobalUsersLatestFirst :many
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
ORDER BY
	created_at DESC
LIMIT
	$1
`

func (q *Queries) GetGlobalUsersLatestFirst(ctx context.Context, limit int32) ([]GlobalUserDetail, error) {
	rows, err := q.db.Query(ctx, getGlobalUsersLatestFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalUserDetail
	for rows.Next() {
		var i GlobalUserDetail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.About,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.ProfilePictureID,
			&i.Status,
			&i.UncompressedProfilePicture,
			&i.ProfilePictureSize,
			&i.ProfilePictureStatus,
			&i.Thumbnail,
			&i.Small,
			&i.Medium,
			&i.Large,
			&i.ExtraLarge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalUsersLatestFirstGreaterThanCursor = `-- name: GetGlobalUsersLatestFirstGreaterThanCursor :many
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
WHERE
	created_at > $2::TIMESTAMPTZ
ORDER BY
	created_at DESC
LIMIT
	$1
`

type GetGlobalUsersLatestFirstGreaterThanCursorParams struct {
	Limit  int32     `json:"limit"`
	Cursor time.Time `json:"cursor"`
}

func (q *Queries) GetGlobalUsersLatestFirstGreaterThanCursor(ctx context.Context, arg GetGlobalUsersLatestFirstGreaterThanCursorParams) ([]GlobalUserDetail, error) {
	rows, err := q.db.Query(ctx, getGlobalUsersLatestFirstGreaterThanCursor, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalUserDetail
	for rows.Next() {
		var i GlobalUserDetail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.About,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.ProfilePictureID,
			&i.Status,
			&i.UncompressedProfilePicture,
			&i.ProfilePictureSize,
			&i.ProfilePictureStatus,
			&i.Thumbnail,
			&i.Small,
			&i.Medium,
			&i.Large,
			&i.ExtraLarge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalUsersLatestFirstLesserThanCursor = `-- name: GetGlobalUsersLatestFirstLesserThanCursor :many
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
WHERE
	created_at < $2::TIMESTAMPTZ
ORDER BY
	created_at DESC
LIMIT
	$1
`

type GetGlobalUsersLatestFirstLesserThanCursorParams struct {
	Limit  int32     `json:"limit"`
	Cursor time.Time `json:"cursor"`
}

func (q *Queries) GetGlobalUsersLatestFirstLesserThanCursor(ctx context.Context, arg GetGlobalUsersLatestFirstLesserThanCursorParams) ([]GlobalUserDetail, error) {
	rows, err := q.db.Query(ctx, getGlobalUsersLatestFirstLesserThanCursor, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalUserDetail
	for rows.Next() {
		var i GlobalUserDetail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.About,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.ProfilePictureID,
			&i.Status,
			&i.UncompressedProfilePicture,
			&i.ProfilePictureSize,
			&i.ProfilePictureStatus,
			&i.Thumbnail,
			&i.Small,
			&i.Medium,
			&i.Large,
			&i.ExtraLarge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalUsersOldestFirst = `-- name: GetGlobalUsersOldestFirst :many
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
ORDER BY
	created_at ASC
LIMIT
	$1
`

func (q *Queries) GetGlobalUsersOldestFirst(ctx context.Context, limit int32) ([]GlobalUserDetail, error) {
	rows, err := q.db.Query(ctx, getGlobalUsersOldestFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalUserDetail
	for rows.Next() {
		var i GlobalUserDetail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.About,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.ProfilePictureID,
			&i.Status,
			&i.UncompressedProfilePicture,
			&i.ProfilePictureSize,
			&i.ProfilePictureStatus,
			&i.Thumbnail,
			&i.Small,
			&i.Medium,
			&i.Large,
			&i.ExtraLarge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalUsersOldestFirstGreaterThanCursor = `-- name: GetGlobalUsersOldestFirstGreaterThanCursor :many
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
WHERE
	created_at > $2::TIMESTAMPTZ
ORDER BY
	created_at ASC
LIMIT
	$1
`

type GetGlobalUsersOldestFirstGreaterThanCursorParams struct {
	Limit  int32     `json:"limit"`
	Cursor time.Time `json:"cursor"`
}

func (q *Queries) GetGlobalUsersOldestFirstGreaterThanCursor(ctx context.Context, arg GetGlobalUsersOldestFirstGreaterThanCursorParams) ([]GlobalUserDetail, error) {
	rows, err := q.db.Query(ctx, getGlobalUsersOldestFirstGreaterThanCursor, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalUserDetail
	for rows.Next() {
		var i GlobalUserDetail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.About,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.ProfilePictureID,
			&i.Status,
			&i.UncompressedProfilePicture,
			&i.ProfilePictureSize,
			&i.ProfilePictureStatus,
			&i.Thumbnail,
			&i.Small,
			&i.Medium,
			&i.Large,
			&i.ExtraLarge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalUsersOldestFirstLesserThanCursor = `-- name: GetGlobalUsersOldestFirstLesserThanCursor :many
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
WHERE
	created_at < $2::TIMESTAMPTZ
ORDER BY
	created_at ASC
LIMIT
	$1
`

type GetGlobalUsersOldestFirstLesserThanCursorParams struct {
	Limit  int32     `json:"limit"`
	Cursor time.Time `json:"cursor"`
}

func (q *Queries) GetGlobalUsersOldestFirstLesserThanCursor(ctx context.Context, arg GetGlobalUsersOldestFirstLesserThanCursorParams) ([]GlobalUserDetail, error) {
	rows, err := q.db.Query(ctx, getGlobalUsersOldestFirstLesserThanCursor, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalUserDetail
	for rows.Next() {
		var i GlobalUserDetail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.About,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.ProfilePictureID,
			&i.Status,
			&i.UncompressedProfilePicture,
			&i.ProfilePictureSize,
			&i.ProfilePictureStatus,
			&i.Thumbnail,
			&i.Small,
			&i.Medium,
			&i.Large,
			&i.ExtraLarge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT
	id, email, name, about, date_of_birth, created_at, profile_picture_id, status, uncompressed_profile_picture, profile_picture_size, profile_picture_status, thumbnail, small, medium, large, extra_large
FROM
	global.user_details
WHERE
	id = $1::UUID
`

func (q *Queries) GetUserById(ctx context.Context, userID uuid.UUID) (GlobalUserDetail, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i GlobalUserDetail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.About,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.ProfilePictureID,
		&i.Status,
		&i.UncompressedProfilePicture,
		&i.ProfilePictureSize,
		&i.ProfilePictureStatus,
		&i.Thumbnail,
		&i.Small,
		&i.Medium,
		&i.Large,
		&i.ExtraLarge,
	)
	return i, err
}

const updateGlobalUserStatus = `-- name: UpdateGlobalUserStatus :one
UPDATE global.users
SET
	status = $1
WHERE
	id = $2
RETURNING
	id,
	email AS username
`

type UpdateGlobalUserStatusParams struct {
	Status GlobalUserStatus `json:"status"`
	ID     uuid.UUID        `json:"id"`
}

type UpdateGlobalUserStatusRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateGlobalUserStatus(ctx context.Context, arg UpdateGlobalUserStatusParams) (UpdateGlobalUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateGlobalUserStatus, arg.Status, arg.ID)
	var i UpdateGlobalUserStatusRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}
