// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package db

import (
	"github.com/google/uuid"
)

type NewTemporaryMediaParams struct {
	ID         uuid.UUID             `json:"id"`
	BucketPath string                `json:"bucketPath"`
	UploadType GlobalMediaUploadType `json:"uploadType"`
	MediaType  GlobalMediaType       `json:"mediaType"`
	UploadID   *string               `json:"uploadId"`
}
