// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

type AddOrganizationRestrictionsParams struct {
	OrgID         uuid.UUID `json:"orgId"`
	RestrictionID uuid.UUID `json:"restrictionId"`
	Value         int32     `json:"value"`
	Info          *string   `json:"info"`
}

const newOrganization = `-- name: NewOrganization :one
INSERT INTO
	global.organizations (
		root_user,
		name,
		description,
		logo,
		cover_image
	)
VALUES
	($1, $2, $3, $4, $5)
RETURNING
	id
`

type NewOrganizationParams struct {
	RootUser    uuid.UUID  `json:"rootUser"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Logo        *uuid.UUID `json:"logo"`
	CoverImage  *uuid.UUID `json:"coverImage"`
}

func (q *Queries) NewOrganization(ctx context.Context, arg NewOrganizationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, newOrganization,
		arg.RootUser,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.CoverImage,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
