// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addServiceDetails = `-- name: AddServiceDetails :exec
INSERT INTO
	global.services (id, name, type)
VALUES
	($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET
	type = excluded.type
`

type AddServiceDetailsParams struct {
	ID   uuid.UUID   `json:"id"`
	Name string      `json:"name"`
	Type interface{} `json:"type"`
}

func (q *Queries) AddServiceDetails(ctx context.Context, arg AddServiceDetailsParams) error {
	_, err := q.db.Exec(ctx, addServiceDetails, arg.ID, arg.Name, arg.Type)
	return err
}
