// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addServiceDetails = `-- name: AddServiceDetails :exec
INSERT INTO
	global.services (
		id,
		name,
		assignable,
		logical_partition
	)
VALUES
	($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET
	assignable = excluded.assignable,
	logical_partition = excluded.logical_partition
`

type AddServiceDetailsParams struct {
	ID               uuid.UUID                         `json:"id"`
	Name             string                            `json:"name"`
	Assignable       bool                              `json:"assignable"`
	LogicalPartition GlobalServiceLogicalPartitionType `json:"logicalPartition"`
}

func (q *Queries) AddServiceDetails(ctx context.Context, arg AddServiceDetailsParams) error {
	_, err := q.db.Exec(ctx, addServiceDetails,
		arg.ID,
		arg.Name,
		arg.Assignable,
		arg.LogicalPartition,
	)
	return err
}

const addServiceHierarchyDetails = `-- name: AddServiceHierarchyDetails :exec
INSERT INTO
	global.service_hierarchy_details (
		service_id,
		hierarchy_name,
		hierarchy_type,
		hierarchy_result
	)
VALUES
	($1, $2, $3, $4)
ON CONFLICT (service_id) DO UPDATE
SET
	hierarchy_name = excluded.hierarchy_name,
	hierarchy_type = excluded.hierarchy_type,
	hierarchy_result = excluded.hierarchy_result
`

type AddServiceHierarchyDetailsParams struct {
	ServiceID       uuid.UUID                    `json:"serviceId"`
	HierarchyName   string                       `json:"hierarchyName"`
	HierarchyType   GlobalServiceHierarchyType   `json:"hierarchyType"`
	HierarchyResult GlobalServiceHierarchyResult `json:"hierarchyResult"`
}

func (q *Queries) AddServiceHierarchyDetails(ctx context.Context, arg AddServiceHierarchyDetailsParams) error {
	_, err := q.db.Exec(ctx, addServiceHierarchyDetails,
		arg.ServiceID,
		arg.HierarchyName,
		arg.HierarchyType,
		arg.HierarchyResult,
	)
	return err
}
