// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addServiceDetails = `-- name: AddServiceDetails :exec
INSERT INTO
	global.services (
		id,
		name,
		assignable,
		logical_partition
	)
VALUES
	($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET
	assignable = excluded.assignable,
	logical_partition = excluded.logical_partition
`

type AddServiceDetailsParams struct {
	ID               uuid.UUID                         `json:"id"`
	Name             string                            `json:"name"`
	Assignable       bool                              `json:"assignable"`
	LogicalPartition GlobalServiceLogicalPartitionType `json:"logicalPartition"`
}

func (q *Queries) AddServiceDetails(ctx context.Context, arg AddServiceDetailsParams) error {
	_, err := q.db.Exec(ctx, addServiceDetails,
		arg.ID,
		arg.Name,
		arg.Assignable,
		arg.LogicalPartition,
	)
	return err
}
