// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_management.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const newManagementUser = `-- name: NewManagementUser :exec
INSERT INTO
	management.users (id)
VALUES
	($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) NewManagementUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, newManagementUser, id)
	return err
}

const removeManagementUser = `-- name: RemoveManagementUser :exec
DELETE FROM management.users
WHERE
	id = $1
`

func (q *Queries) RemoveManagementUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeManagementUser, id)
	return err
}
