// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_group.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const newUserGroup = `-- name: NewUserGroup :one
INSERT INTO
	management.user_groups (name, description)
VALUES
	($1, $2)
RETURNING
	id,
	name,
	description,
	created_at
`

type NewUserGroupParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type NewUserGroupRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

func (q *Queries) NewUserGroup(ctx context.Context, arg NewUserGroupParams) (NewUserGroupRow, error) {
	row := q.db.QueryRow(ctx, newUserGroup, arg.Name, arg.Description)
	var i NewUserGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
