// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: permission.sql

package db_actions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addApplicationPermission = `-- name: AddApplicationPermission :exec
INSERT INTO
	application.permissions (
		key,
		service_name,
		name,
		description,
		required_resources
	)
VALUES
	($1, $2, $3, $4, $5)
`

type AddApplicationPermissionParams struct {
	Key               string
	ServiceName       string
	Name              string
	Description       pgtype.Text
	RequiredResources []GlobalPermissionResourceType
}

func (q *Queries) AddApplicationPermission(ctx context.Context, arg AddApplicationPermissionParams) error {
	_, err := q.db.Exec(ctx, addApplicationPermission,
		arg.Key,
		arg.ServiceName,
		arg.Name,
		arg.Description,
		arg.RequiredResources,
	)
	return err
}

const addManagementPermission = `-- name: AddManagementPermission :exec
INSERT INTO
	management.permissions (
		key,
		service_name,
		name,
		description,
		required_resources
	)
VALUES
	($1, $2, $3, $4, $5)
`

type AddManagementPermissionParams struct {
	Key               string
	ServiceName       string
	Name              string
	Description       pgtype.Text
	RequiredResources []GlobalPermissionResourceType
}

func (q *Queries) AddManagementPermission(ctx context.Context, arg AddManagementPermissionParams) error {
	_, err := q.db.Exec(ctx, addManagementPermission,
		arg.Key,
		arg.ServiceName,
		arg.Name,
		arg.Description,
		arg.RequiredResources,
	)
	return err
}
