// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db_actions

import (
	"context"
)

type Querier interface {
	AddApplicationPermission(ctx context.Context, arg AddApplicationPermissionParams) error
	AddManagementPermission(ctx context.Context, arg AddManagementPermissionParams) error
	AddService(ctx context.Context, arg AddServiceParams) error
	AddServiceHierarchyDetails(ctx context.Context, arg AddServiceHierarchyDetailsParams) error
	BatchAddApplicationPermission(ctx context.Context, permissions []byte) error
	BatchAddManagementPermission(ctx context.Context, permissions []byte) error
}

var _ Querier = (*Queries)(nil)
