// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: services.sql

package db_actions

import (
	"context"
)

const addService = `-- name: AddService :exec
INSERT INTO
	global.services (
		name,
		assignable,
		logical_partition
	)
VALUES
	($1, $2, $3)
ON CONFLICT (name) DO UPDATE
SET
	assignable = excluded.assignable,
	logical_partition = excluded.logical_partition
`

type AddServiceParams struct {
	Name             string                            `json:"name"`
	Assignable       bool                              `json:"assignable"`
	LogicalPartition GlobalServiceLogicalPartitionType `json:"logicalPartition"`
}

func (q *Queries) AddService(ctx context.Context, arg AddServiceParams) error {
	_, err := q.db.Exec(ctx, addService, arg.Name, arg.Assignable, arg.LogicalPartition)
	return err
}

const addServiceHierarchyDetails = `-- name: AddServiceHierarchyDetails :exec
INSERT INTO
	global.service_hierarchy_details (
		service_name,
		hierarchy_name,
		hierarchy_type,
		hierarchy_result
	)
VALUES
	($1, $2, $3, $4)
ON CONFLICT (service_name) DO UPDATE
SET
	hierarchy_name = excluded.hierarchy_name,
	hierarchy_type = excluded.hierarchy_type,
	hierarchy_result = excluded.hierarchy_result
`

type AddServiceHierarchyDetailsParams struct {
	ServiceName     string                       `json:"serviceName"`
	HierarchyName   string                       `json:"hierarchyName"`
	HierarchyType   GlobalServiceHierarchyType   `json:"hierarchyType"`
	HierarchyResult GlobalServiceHierarchyResult `json:"hierarchyResult"`
}

func (q *Queries) AddServiceHierarchyDetails(ctx context.Context, arg AddServiceHierarchyDetailsParams) error {
	_, err := q.db.Exec(ctx, addServiceHierarchyDetails,
		arg.ServiceName,
		arg.HierarchyName,
		arg.HierarchyType,
		arg.HierarchyResult,
	)
	return err
}
