// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: services.sql

package db_actions

import (
	"context"
)

const addService = `-- name: AddService :exec
INSERT INTO
	global.services (
		name,
		permission_only,
		logical_partition
	)
VALUES
	($1, $2, $3)
`

type AddServiceParams struct {
	Name             string
	PermissionOnly   bool
	LogicalPartition GlobalServiceLogicalPartitionType
}

func (q *Queries) AddService(ctx context.Context, arg AddServiceParams) error {
	_, err := q.db.Exec(ctx, addService, arg.Name, arg.PermissionOnly, arg.LogicalPartition)
	return err
}

const addServiceHierarchyDetails = `-- name: AddServiceHierarchyDetails :exec
INSERT INTO
	global.service_hierarchy_details (
		service_name,
		hierarchy_name,
		hierarchy_type,
		hierarchy_result
	)
VALUES
	($1, $2, $3, $4)
`

type AddServiceHierarchyDetailsParams struct {
	ServiceName     string
	HierarchyName   string
	HierarchyType   GlobalServiceHierarchyType
	HierarchyResult GlobalServiceHierarchyResult
}

func (q *Queries) AddServiceHierarchyDetails(ctx context.Context, arg AddServiceHierarchyDetailsParams) error {
	_, err := q.db.Exec(ctx, addServiceHierarchyDetails,
		arg.ServiceName,
		arg.HierarchyName,
		arg.HierarchyType,
		arg.HierarchyResult,
	)
	return err
}
